<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Repository\IGrupoUnidadeMedidaRepository.cs" />
    <Compile Remove="Interfaces\Repository\IUnidadeMedidaOdbcRepository.cs" />
    <Compile Remove="Interfaces\Repository\UnidadeMedidaRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Geral\" />
    <Folder Include="Dtos\Compra\" />
    <Folder Include="Dtos\Relatorio\" />
    <Folder Include="Dtos\Venda\" />
    <Folder Include="Entidades\Compra\" />
    <Folder Include="Entidades\Relatorio\" />
    <Folder Include="Entidades\Venda\" />
    <Folder Include="Enums\Geral\" />
    <Folder Include="Enums\Compra\" />
    <Folder Include="Enums\Relatorio\" />
    <Folder Include="Enums\Venda\" />
    <Folder Include="Interfaces\Repository\Geral\" />
    <Folder Include="Interfaces\Repository\Compra\" />
    <Folder Include="Interfaces\Repository\Venda\" />
    <Folder Include="Interfaces\Service\Geral\" />
    <Folder Include="Interfaces\Service\Compra\" />
    <Folder Include="Interfaces\Service\Relatorio\" />
    <Folder Include="Interfaces\Service\Venda\" />
    <Folder Include="Models\Geral\" />
    <Folder Include="Models\Relatorio\" />
    <Folder Include="Models\Venda\" />
    <Folder Include="Utils\" />
    <Folder Include="Extensoes\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Interfaces\Repository\IGrupoUnidadeMedidaRepository.cs" />
    <None Include="Interfaces\Repository\IUnidadeMedidaOdbcRepository.cs" />
    <None Include="Interfaces\Repository\UnidadeMedidaRepository.cs" />
  </ItemGroup>

</Project>
